title: >
  编程语言基础：Agda 描述

description: >
  编程语言基础：Agda 描述

license: Creative Commons Attribution 4.0 International License
license-file: https://creativecommons.org/licenses/by/4.0/

# To include a new author, add them below in the order in which they are to be
# displayed in the author list. If they have made contributions as an author via
# GitHub, their username MUST be included in the list.
authors:
  - name: Philip Wadler
    email: wadler@inf.ed.ac.uk
    corresponding: true
    github_username: wadler
  - name: Wen Kokke
    email: wen.kokke@ed.ac.uk
    corresponding: true
    github_username: wenkokke
    twitter_username: wenkokke

google_analytics: "UA-125055580-1"

repository: roger-uw/PLFA-zh
branch: dev

baseurl: "/plfa-zh-test"
url: "https://roger-uw.github.io"
markdown: kramdown
theme: minima
exclude:
  - "hs/"
  - "src/"
  - "extra/"
  - "vendor/"
  - "*.lagda"
  - "Gemfile"
  - "Gemfile.lock"
  - "scripts/"
contributors:
- github_username: mdimjasevic
  name: Marko Dimjašević
- github_username: roger-uw
  name: roger-uw
- github_username: Kwezan
  name: Zbigniew Stanasiuk
- github_username: ywata
  name: Yasu Watanabe
- github_username: fangyi-zhou
  name: Fangyi Zhou
- github_username: Fingerzam
  name: Juhana Laurinharju
- github_username: Cubesoup
  name: Chad Nester
- github_username: OlingCat
  name: Oling Cat
- github_username: phi16
  name: phi16
- github_username: jonaprieto
  name: Jonathan Prieto
- github_username: livecodealex
  name: Alexandru Brisan
- github_username: michel-steuwer
  name: Michel Steuwer
- github_username: caryoscelus
  name: caryoscelus
- github_username: lzmartinico
  name: Lorenzo Martinico
- github_username: whxvd
  name: Sebastian Miele
- github_username: murilogiacometti
  name: Murilo Giacometti Rocha
- github_username: spwhitt
  name: Spencer Whitt
- github_username: LightAndLight
  name: Isaac Elliott
- github_username: iblech
  name: Ingo Blechschmidt
- github_username: Teggy
  name: Torsten Grust
- github_username: k4rtik
  name: Kartik Singhal
- github_username: philderbeast
  name: Phil de Joux
- github_username: stepchowfun
  name: Stephan Boyer
- github_username: zgrannan
  name: Zack Grannan
- github_username: navaati
  name: Léo Gillot-Lamure
- github_username: kwxm
  name: Kenneth MacKenzie
- github_username: moleike
  name: Alexandre Moreno
- github_username: jsiek
  name: Jeremy G. Siek
- github_username: laMudri
  name: James Wood
- github_username: kranich
  name: Stefan Kranich
- github_username: rodamber
  name: Rodrigo Bernardo
- github_username: omelkonian
  name: Orestis Melkonian
- github_username: dalpd
  name: Deniz Alp
- github_username: potato4444
  name: Nathaniel Carroll

